instauto/api/actions/profile.py
=> Add missing argument to _request call.

README.md, examples/friendships/approve_all_follow_requests.py, examples/friendships/approve_follow_request_of_specific_user.py, examples/friendships/create_friendship.py, examples/friendships/destroy_friendship.py, examples/friendships/get_followers.py, examples/friendships/get_following.py, examples/friendships/remove_follower.py, examples/friendships/show_friendship.py, examples/post/comment_post.py, examples/post/like_post.py, examples/post/post_retrieve_by_user.py, examples/post/save_post.py, examples/post/unlike_post.py, examples/post/upload_image.py, examples/profile/update_biography.py, examples/profile/update_gender.py, examples/profile/update_profile.py, examples/search/get_user_id_from_username.py, instauto/api/actions/friendships.py, instauto/api/actions/post.py, instauto/api/actions/profile.py, instauto/api/actions/search.py, instauto/api/actions/structs/__init__.py, instauto/api/actions/structs/friendships.py, instauto/api/actions/structs/post.py, instauto/api/actions/structs/profile.py, instauto/api/actions/structs/search.py
e.g. `friendship.ShowFriendship` -> `friendship.Show`
=> Update class names to prevent repetition. 

README.md, examples/friendships/approve_all_follow_requests.py, examples/friendships/approve_follow_request_of_specific_user.py, examples/friendships/create_friendship.py, examples/friendships/destroy_friendship.py, examples/friendships/get_followers.py, examples/friendships/get_following.py, examples/friendships/remove_follower.py, examples/friendships/show_friendship.py, instauto/api/actions/friendships.py
=> Update function names in actions.friendships

instauto/api/actions/structs/post.py
=> fix: posting of comments

instauto/api/actions/request.py
Removed the walrus operators to make the package compatible with python versions before 3.7
=> Removed Walrus operators for more compatibility

.gitignore, examples/post/upload_image.py, examples/post/upload_image_with_location.py, instauto/api/actions/structs/common.py, instauto/api/actions/structs/tests/test_common.py, instauto/api/client.py
=> 9: test common.base

instauto/api/actions/authentication.py, instauto/api/actions/stubs.py
=> fix: remove python3.8 feature

instauto/api/actions/helpers.py, instauto/api/actions/post.py, instauto/api/actions/request.py, instauto/api/actions/structs/common.py, instauto/api/actions/structs/post.py, original_requests/post/upload.json
=> fix: add device details to upload image request

instauto/api/actions/structs/post.py
See at https://github.com/stanvanrooy/instauto/issues/79#issue-721803812
=> Fix for Issue #79

examples/post/upload_image_to_feed.py, examples/post/upload_image_to_story.py, examples/post/upload_image_with_location_to_feed.py, instauto/api/actions/post.py, instauto/api/actions/structs/common.py, instauto/api/actions/structs/post.py, instauto/api/structs.py
=> feat: upload images to story

instauto/api/actions/post.py
Thanks for explaining this to me <3
=> bugfix Issue #91

examples/post/post_get_likers.py, instauto/api/actions/post.py, instauto/api/actions/structs/post.py, instauto/api/actions/tests/media.py, original_requests/post/get_likers.json
Added functionality to get all likers of single media, also added test and one example
=> get_likers of media

.gitignore, instauto/api/actions/request.py, instauto/api/actions/structs/common.py
=> 97 fix non serializable

instauto/api/actions/authentication.py
=> fix: KeyError if challenge was requested during login

instauto/helpers/common.py, instauto/helpers/post.py, instauto/helpers/search.py
=> feat: add helper methods for (almost?) all actions.

instauto/api/actions/structs/post.py
Theres a typo in the Comment class with make commenting not work.
But this little change will fix it, I tested it.
=> Update post.py - fix commenting

instauto/bot/bot.py, instauto/bot/input.py, instauto/helpers/friendships.py
Add `delay_tolerance_delta` attribute to set random time window when to perform the next action
Also added possibility to input user accounts manual to the bot by calling `from_user_list`
=> Add time window to vary delay between actions and fix helpers.get_following inconsistent ApiClient calls

examples/profile/profile_info.py, examples/profile/update_biography.py, examples/profile/update_password.py, examples/profile/update_picture.py, examples/profile/update_profile.py, instauto/api/actions/post.py, instauto/api/actions/profile.py, instauto/api/actions/structs/post.py, instauto/api/actions/structs/profile.py, instauto/api/structs.py
=> feat: update profile picture

instauto/helpers/search.py
Fixes #154. I tested `search_username()` function, it is working now.
=> Fix json parsing in search_username()

instauto/helpers/friendships.py
Hi, I'm new to GitHub and this is my first pull request 😁. Please let me know if there is anything I could do better for the next time I create one.
Besides adding the username argument for two helper functions, as issue #172 addressed, I also made two tiny edits in the docstrings (excluding the edits regarding the new username argument):
1. **get_following function:** changed _"Retrieve the first x amount of users that follow an account."_ to _"Retrieve the first x amount of users that an account is following."_ (I thought the prior version sounded a bit mistakable. I didn't want to open a new issue for such a tiny change but if you don't like it, I'll, of course, change it back)
2. **unfollow_user function:** In the arguments-section, it said "user_id/username: the user_id/username of …
=> Fix for Issue #172 - Add arguments to helper functions (+ docstring edits)

examples/api/post/archive_post.py, examples/api/post/unarchive_post.py, instauto/api/actions/post.py, instauto/api/actions/structs/post.py, requirements.txt
Added archive and unarchive for posts, also changed requests version in requirements to prevent conflict
=> Added archive and unarchive for posts

instauto/bot/input.py
=> fix: change order of parameters

instauto/helpers/friendships.py
=> fix: client.unfollow_user -> client.user_unfollow

instauto/bot/bot.py, instauto/bot/input.py
=> fix: use property instead of __getitem__

instauto/api/client.py
I want to use instauto with persistent cookies but instead of saving to file i'd like to save credentials in a redis store (cache).
So here's little tweak to allow to save session data as plain json string
=> save & load from/to json
